name: HackerOS
options:
  bundleIdPrefix: com.hackeros
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "0.8"
    CURRENT_PROJECT_VERSION: "10"
targets:
  HackerOS:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hackeros.app
        INFOPLIST_FILE: Info.plist
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1,2"
